name: Sample

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install cypress
        run: npm install cypress

      - name: Install cypress-drag-and-drop
        run: npm install --save-dev @4tw/cypress-drag-drop

      - name: Install cypress-mochawesome-reporter
        run: npm install --save-dev cypress-mochawesome-reporter

      - name: Run e2e:workshop
        run: npx cypress run --spec "cypress/e2e/workshop.cy.js"

      - name: publish report
        uses: actions/upload-artifact@v4
        with:
          path: ./cypress/reports/html/.html
          name: html-report
