name: Sample

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install cypress
        uses: npm install cypress

      - name: Install cypress-drag-and-drop
        uses: npm install --save-dev @4tw/cypress-drag-drop

      - name: Run e2e:workshop
        uses: npx cypress run --spec "cypress/e2e/workshop.cy.js"

      # - name: Install cypress-mochawesome-reporter
      #   uses: npm install --save-dev cypress-mochawesome-reporter

      # - name: publish report
      #   uses: actions/upload-artifact@v4
      #   with:
      #     path: ./cypress/reports/html/.html
      #     name: html-report
